# syntax=docker/dockerfile:1
FROM python:3.8-slim-buster

WORKDIR /exp

COPY ./docker/requirements.txt /exp/requirements.txt
RUN pip3 install --no-cache-dir -r /exp/requirements.txt

COPY ./svm_gamma=0.001_C=0.5.joblib /exp/
COPY ./api/* /exp/

WORKDIR /exp
EXPOSE 5000
CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]

